[package]
name = "coding_test"
version = "0.1.0"
edition = "2021"

[dependencies]
rust_decimal = "1.23.1"
log = "0.4.17"
simple-logging = "2.0.2"
csv = "1.1.6"
serde = { version = "1.0.137", features = ["derive"] }
anyhow = "1.0.57"

[profile.dev.package."*"]
opt-level = 3